#!/usr/bin/env python3

import argparse
from bluefang import bluetooth

COMMANDS = [
    'connect',
    'disconnect',
    'info',
    'msg',
    'register-agent',
    'register-profile',
    'unregister-profile'
]

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog='bluetooth-cli', description='Invoke Bluetooth commands')
    parser.add_argument('command', choices=COMMANDS, help='The command to execute')
    parser.add_argument('arguments', metavar='(args)', type=str, nargs='+', help='Arguments used by command')

    result = parser.parse_args()
    command = result.command
    arguments = result.arguments

    bluetooth = bluetooth.Bluetooth()

    if command == 'connect':
        bluetooth.connect(arguments[0])
    elif command == 'disconnect':
        bluetooth.disconnect(arguments[0])
    elif command == 'info':
        bluetooth.info()
    elif command == 'msg':
        if bluetooth.isConnectionEstablished(): #TODO Verify connection is an HID connection?
            bluetooth.sendHIDMessage(arguments)
        else:
            raise Error("Connection must be established before messages can be sent")
    elif command == 'pair':
        bluetooth.pair()
    elif command == 'register-profile':
        bluetooth.registerProfile(arguments[0])
    elif command == 'unregister-profile':
        bluetooth.unregisterProfile(arguments[0])
    else:
        raise Error("Unknown command: %s" % command)
