#!/bin/sh
set -e

apt-get update
apt-get install -qy python3 python3-pip git build-essential python3-dev pkg-config python3-dbus \
libdbus-1-dev libical-dev libreadline-dev bluetooth bluez blueman libbluetooth-dev libdbus-glib-1-dev \
bluetooth bluez blueman libbluetooth-dev python3-gi dbus dbus-x11 python3-venv
